name: challenge_delivery_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.3
  google_fonts: ^2.3.2
  paulonia_cache_image: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - images/a_dot_ham.jpeg
